services:
  - type: web
    name: isewr-backend
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: CLIPDROP_API_KEY
        sync: false
      - key: IMAGINE_ART_API_KEY
        sync: false
      - key: SIGHTENGINE_API_USER
        sync: false
      - key: SIGHTENGINE_API_SECRET
        sync: false
      - key: GOOGLE_CLOUD_PROJECT
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: RENDER
        value: true
    regions:
      - oregon